-- 创建商品表
CREATE TABLE IF NOT EXISTS `product` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` varchar(100) NOT NULL COMMENT '商品名称',
    `description` varchar(255) DEFAULT NULL COMMENT '商品简介',
    `category_id` bigint(20) NOT NULL COMMENT '分类ID',
    `category_name` varchar(50) NOT NULL COMMENT '分类名称',
    `brand_id` bigint(20) DEFAULT NULL COMMENT '品牌ID',
    `brand_name` varchar(50) DEFAULT NULL COMMENT '品牌名称',
    `price` decimal(10,2) NOT NULL COMMENT '商品价格',
    `original_price` decimal(10,2) DEFAULT NULL COMMENT '原价',
    `main_image` varchar(255) NOT NULL COMMENT '主图',
    `images` text COMMENT '图片集，多个图片URL以逗号分隔',
    `detail` text COMMENT '商品详情',
    `specs` text COMMENT '规格参数，JSON格式',
    `stock` int(11) NOT NULL DEFAULT '0' COMMENT '库存',
    `sales` int(11) NOT NULL DEFAULT '0' COMMENT '销量',
    `rating` double(2,1) DEFAULT '5.0' COMMENT '评分：1-5',
    `comment_count` int(11) DEFAULT '0' COMMENT '评论数量',
    `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '状态：0-下架，1-上架',
    `seller_id` bigint(20) NOT NULL COMMENT '卖家ID',
    `seller_name` varchar(50) NOT NULL COMMENT '卖家名称',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_category_id` (`category_id`),
    KEY `idx_brand_id` (`brand_id`),
    KEY `idx_seller_id` (`seller_id`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品表'; 