-- 创建低空旅客表
CREATE TABLE IF NOT EXISTS `low_altitude_passenger` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `title` varchar(100) NOT NULL COMMENT '标题',
    `description` text NOT NULL COMMENT '描述',
    `cover_image` varchar(255) NOT NULL COMMENT '封面图片',
    `images` text COMMENT '图片集，多个图片URL以逗号分隔',
    `departure_location` varchar(100) NOT NULL COMMENT '出发地点',
    `arrival_location` varchar(100) NOT NULL COMMENT '到达地点',
    `departure_time` datetime NOT NULL COMMENT '出发时间',
    `arrival_time` datetime NOT NULL COMMENT '到达时间',
    `duration` int(11) NOT NULL COMMENT '飞行时长（分钟）',
    `capacity` int(11) NOT NULL COMMENT '载客容量',
    `booked_count` int(11) NOT NULL DEFAULT '0' COMMENT '已预订人数',
    `price` decimal(10,2) NOT NULL COMMENT '价格',
    `drone_model` varchar(100) NOT NULL COMMENT '无人机型号',
    `pilot_name` varchar(50) NOT NULL COMMENT '飞行员姓名',
    `pilot_license` varchar(50) NOT NULL COMMENT '飞行员执照编号',
    `pilot_experience` varchar(255) NOT NULL COMMENT '飞行员经验',
    `safety_measures` text NOT NULL COMMENT '安全措施',
    `weather_requirements` varchar(255) NOT NULL COMMENT '天气要求',
    `cancellation_policy` varchar(255) NOT NULL COMMENT '取消政策',
    `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '状态：0-待上架，1-已上架，2-已下架',
    `user_id` bigint(20) NOT NULL COMMENT '创建者ID',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_departure_time` (`departure_time`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='低空旅客表'; 